apiVersion: v1
kind: Secret
metadata:
  name: laravel-secret
  namespace: laravel-app
type: Opaque
data:
  # APP_KEY Laravel (doit être en base64)
  # Valeur : base64:vUuwZJTGLlfKP0ejBmLsiVRpqbL1VCapSWwRkU2N298=
  APP_KEY: YmFzZTY0OnZVdXdaSlRHbGxmS1AwZWpCbUxzaVZScHFiTDFWQ2FwU1d3UmtVMk4yOTg9
