apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: laravel-app
type: Opaque
data:
  # Mot de passe root MySQL vide (chaîne vide encodée en base64)
  MYSQL_ROOT_PASSWORD: ""
  # Nom de la base de données : laravel_db (encodé en base64)
  MYSQL_DATABASE: bGFyYXZlbF9kYg==
